from enum import Enum

class RosterType(Enum):
    ROSTER_TYPE_UNSPECIFIED = (0, "ROSTER_TYPE_UNSPECIFIED")
    ROSTER_TYPE_COMBAT = (1, "ROSTER_TYPE_COMBAT")
    ROSTER_TYPE_RESERVE = (2, "ROSTER_TYPE_RESERVE")
    ROSTER_TYPE_ELOA = (3, "ROSTER_TYPE_ELOA")
    ROSTER_TYPE_WALL_OF_HONOR = (4, "ROSTER_TYPE_WALL_OF_HONOR")
    ROSTER_TYPE_ARLINGTON = (5, "ROSTER_TYPE_ARLINGTON")
    ROSTER_TYPE_PAST_MEMBERS = (6, "ROSTER_TYPE_PAST_MEMBERS")

class RecordType(Enum):
    RECORD_TYPE_UNSPECIFIED = (0, "RECORD_TYPE_UNSPECIFIED")
    RECORD_TYPE_PROMOTION = (1, "RECORD_TYPE_PROMOTION")
    RECORD_TYPE_OPERATION = (2, "RECORD_TYPE_OPERATION")
    RECORD_TYPE_TRANSFER = (3, "RECORD_TYPE_TRANSFER")
    RECORD_TYPE_DISCIPLINARY = (4, "RECORD_TYPE_DISCIPLINARY")
    RECORD_TYPE_DISCHARGE = (5, "RECORD_TYPE_DISCHARGE")
    RECORD_TYPE_ASSIGNMENT = (6, "RECORD_TYPE_ASSIGNMENT")
    RECORD_TYPE_NAME_CHANGE = (7, "RECORD_TYPE_NAME_CHANGE")
    RECORD_TYPE_ELOA = (8, "RECORD_TYPE_ELOA")
    RECORD_TYPE_GRADUATION = (9, "RECORD_TYPE_GRADUATION")